apiVersion: v1
kind: Namespace
metadata:
  name: blue
---
apiVersion: v1
kind: Pod
metadata:
  name: blue-1
  namespace: blue
  labels:
    app: blue
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: blue-2
  namespace: blue
  labels:
    app: blue
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blue
  namespace: blue
spec:
  selector:
    app: blue
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
