apiVersion: v1
kind: Namespace
metadata:
  name: blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deploy
  namespace: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-web
  template:
    metadata:
      labels:
        app: blue-web
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blue
  namespace: blue
spec:
  selector:
    app: blue-web
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
