apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-leak
  labels:
    app: memory-leak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-leak
  template:
    metadata:
      labels:
        app: memory-leak
    spec:
      containers:
      - name: memory-leak-container
        image: ongja/mem-leak:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: memory-leak-service
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30007
    targetPort: 5000
  selector:
    app: memory-leak
