apiVersion: v1
kind: Namespace
metadata:
  name: red
---
apiVersion: v1
kind: Pod
metadata:
  name: red-1
  namespace: red
  labels:
    app: red
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: red-2
  namespace: red
  labels:
    app: red
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: red
  namespace: red
spec:
  selector:
    app: red
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
