apiVersion: v1
kind: Namespace
metadata:
  name: red
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-deploy
  namespace: red
spec:
  replicas: 2
  selector:
    matchLabels:
      app: red-web
  template:
    metadata:
      labels:
        app: red-web
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: red
  namespace: red
spec:
  selector:
    app: red-web
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
